### ISSUE TITLE
Build window fail

### ISSUE THREAD

**Issue by zuozhehao** [brutella/hap#2]
```go
goroutine 18 [running]:
github.com/brutella/dnssd.(*Service).IPsAtInterface(0xc0000736b8, 0x0)
        D:/***/github.com/brutella/dnssd@v1.2.2/service.go:150 +0x3d
github.com/brutella/dnssd.A({{0xc000212020, 0x4}, {0x6d4654, 0x9}, {0x6d3039, 0x5}, {0xc000212024, 0xc}, 0xc000206120, 0x0, ...}, ...)
        D:/***/github.com/brutella/dnssd@v1.2.2/dns.go:116 +0x39
github.com/brutella/dnssd.containsConflictingAnswers(0xc000406090, 0xc000214020)
        D:/***/github.com/brutella/dnssd@v1.2.2/responder.go:465 +0xbb
github.com/brutella/dnssd.findConflicts(0xc000406090, {0xc00040a010, 0x1, 0x1?})
        D:/***/github.com/brutella/dnssd@v1.2.2/responder.go:446 +0x9b
github.com/brutella/dnssd.(*responder).handleRequest(0xc000210000, 0xc000406090)
        D:/***/github.com/brutella/dnssd@v1.2.2/responder.go:238 +0x195
github.com/brutella/dnssd.(*responder).respond(0xc000210000, {0x775710, 0xc00022c040})
        D:/***/github.com/brutella/dnssd@v1.2.2/responder.go:203 +0x1d4
github.com/brutella/dnssd.(*responder).Respond(0xc000210000, {0x775710, 0xc00022c040})
        D:/***/github.com/brutella/dnssd@v1.2.2/responder.go:113 +0x3ef
github.com/brutella/hap.(*Server).listenAndServe.func1()
        D:/***/github.com/brutella/hap@v0.0.14/server.go:205 +0x37
created by github.com/brutella/hap.(*Server).listenAndServe
        D:/***/github.com/brutella/hap@v0.0.14/server.go:204 +0x465

Process finished with the exit code 2
```
Same question https://github.com/brutella/hc/issues/201

**Comment by brutella** [comment]
I'm still confused on why `s.ifaceIPs` is nil only on Windows? Doesn't make any sense!

**Comment by zuozhehao** [comment]
> I'm still confused on why `s.ifaceIPs` is nil only on Windows? Doesn't make any sense!

I haven't added any code yet, just use the example code
```
package main

import (
	"github.com/brutella/hap"
	"github.com/brutella/hap/accessory"

	"context"
	"log"
	"os"
	"os/signal"
	"syscall"
)

func main() {
	// Create the switch accessory.
	a := accessory.NewSwitch(accessory.Info{
		Name: "Lamp",
	})

	// Store the data in the "./db" directory.
	fs := hap.NewFsStore("./db")

	// Create the hap server.
	server, err := hap.NewServer(fs, a.A)
	if err != nil {
		// stop if an error happens
		log.Panic(err)
	}

	// Setup a listener for interrupts and SIGTERM signals
	// to stop the server.
	c := make(chan os.Signal)
	signal.Notify(c, os.Interrupt)
	signal.Notify(c, syscall.SIGTERM)

	ctx, cancel := context.WithCancel(context.Background())
	go func() {
		<-c
		// Stop delivering signals.
		signal.Stop(c)
		// Cancel the context to stop the server.
		cancel() 
	}()

	// Run the server.
	server.ListenAndServe(ctx)
}
```

**Comment by zuozhehao** [comment]
![image](https://user-images.githubusercontent.com/4464252/160354314-2f6102f0-5bf2-442f-a4bf-eaab7b89f9d8.png)
@brutella  Got a virtual network card?

**Comment by hepeichun** [comment]
> > I'm still confused on why `s.ifaceIPs` is nil only on Windows? Doesn't make any sense!
> 
> I haven't added any code yet, just use the example code
> 
> ```
> package main
> 
> import (
> 	"github.com/brutella/hap"
> 	"github.com/brutella/hap/accessory"
> 
> 	"context"
> 	"log"
> 	"os"
> 	"os/signal"
> 	"syscall"
> )
> 
> func main() {
> 	// Create the switch accessory.
> 	a := accessory.NewSwitch(accessory.Info{
> 		Name: "Lamp",
> 	})
> 
> 	// Store the data in the "./db" directory.
> 	fs := hap.NewFsStore("./db")
> 
> 	// Create the hap server.
> 	server, err := hap.NewServer(fs, a.A)
> 	if err != nil {
> 		// stop if an error happens
> 		log.Panic(err)
> 	}
> 
> 	// Setup a listener for interrupts and SIGTERM signals
> 	// to stop the server.
> 	c := make(chan os.Signal)
> 	signal.Notify(c, os.Interrupt)
> 	signal.Notify(c, syscall.SIGTERM)
> 
> 	ctx, cancel := context.WithCancel(context.Background())
> 	go func() {
> 		<-c
> 		// Stop delivering signals.
> 		signal.Stop(c)
> 		// Cancel the context to stop the server.
> 		cancel() 
> 	}()
> 
> 	// Run the server.
> 	server.ListenAndServe(ctx)
> }
> ```

@brutella @zuozhehao 
This might have something to do with IPv6.

**Comment by zuozhehao** [comment]
I am on [dns.go#L115](https://github.com/brutella/dnssd/blob/18549ed14e7cf31c33f50fd8e4c84d26c516de6c/dns.go#L115) added log `runtime.Caller` 



```
[fe80::d861:2861:e8c4:6bc5 192.168.14.205]-7677278-D:/Go/pkg/mod/github.com/brutella/dnssd@v1.2.2/dns.go-121
[fe80::d861:2861:e8c4:6bc5 192.168.14.205]-7701220-D:/Go/pkg/mod/github.com/brutella/dnssd@v1.2.2/probe.go-208
[fe80::d861:2861:e8c4:6bc5 192.168.14.205]-7697306-D:/Go/pkg/mod/github.com/brutella/dnssd@v1.2.2/probe.go-109
[fe80::d861:2861:e8c4:6bc5 192.168.14.205]-7695450-D:/Go/pkg/mod/github.com/brutella/dnssd@v1.2.2/probe.go-62
[fe80::d861:2861:e8c4:6bc5 192.168.14.205]-7693022-D:/Go/pkg/mod/github.com/brutella/dnssd@v1.2.2/probe.go-39
[fe80::d861:2861:e8c4:6bc5 192.168.14.205]-7715155-D:/Go/pkg/mod/github.com/brutella/dnssd@v1.2.2/responder.go-164
[fe80::d861:2861:e8c4:6bc5 192.168.14.205]-7710491-D:/Go/pkg/mod/github.com/brutella/dnssd@v1.2.2/responder.go-103
[fe80::d861:2861:e8c4:6bc5 192.168.14.205]-8070166-D:/Go/pkg/mod/github.com/brutella/hap@v0.0.14/server.go-206

[fe80::e57b:5a49:9fa:c08d 192.168.56.1]-7677278-D:/Go/pkg/mod/github.com/brutella/dnssd@v1.2.2/dns.go-121
[fe80::e57b:5a49:9fa:c08d 192.168.56.1]-7701220-D:/Go/pkg/mod/github.com/brutella/dnssd@v1.2.2/probe.go-208
[fe80::e57b:5a49:9fa:c08d 192.168.56.1]-7697306-D:/Go/pkg/mod/github.com/brutella/dnssd@v1.2.2/probe.go-109
[fe80::e57b:5a49:9fa:c08d 192.168.56.1]-7695450-D:/Go/pkg/mod/github.com/brutella/dnssd@v1.2.2/probe.go-62
[fe80::e57b:5a49:9fa:c08d 192.168.56.1]-7693022-D:/Go/pkg/mod/github.com/brutella/dnssd@v1.2.2/probe.go-39
[fe80::e57b:5a49:9fa:c08d 192.168.56.1]-7715155-D:/Go/pkg/mod/github.com/brutella/dnssd@v1.2.2/responder.go-164
[fe80::e57b:5a49:9fa:c08d 192.168.56.1]-7710491-D:/Go/pkg/mod/github.com/brutella/dnssd@v1.2.2/responder.go-103
[fe80::e57b:5a49:9fa:c08d 192.168.56.1]-8070166-D:/Go/pkg/mod/github.com/brutella/hap@v0.0.14/server.go-206

```

panic log
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x10 pc=0x76015d]

goroutine 18 [running]:
github.com/brutella/dnssd.(*Service).IPsAtInterface(0xc00006d6b8, 0x0)
	D:/Go/pkg/mod/github.com/brutella/dnssd@v1.2.2/service.go:150 +0x3d
github.com/brutella/dnssd.A({{0xc000212020, 0x4}, {0x859677, 0x9}, {0x857efc, 0x5}, {0xc000212024, 0xc}, 0xc0002060f0, 0x0, ...}, ...)
	D:/Go/pkg/mod/github.com/brutella/dnssd@v1.2.2/dns.go:117 +0x39
github.com/brutella/dnssd.containsConflictingAnswers(0xc000306198, 0xc000214020)
	D:/Go/pkg/mod/github.com/brutella/dnssd@v1.2.2/responder.go:465 +0xbb
github.com/brutella/dnssd.findConflicts(0xc000306198, {0xc00031c008, 0x1, 0x1?})
	D:/Go/pkg/mod/github.com/brutella/dnssd@v1.2.2/responder.go:446 +0x9b
github.com/brutella/dnssd.(*responder).handleRequest(0xc000210000, 0xc000306198)
	D:/Go/pkg/mod/github.com/brutella/dnssd@v1.2.2/responder.go:238 +0x195
github.com/brutella/dnssd.(*responder).respond(0xc000210000, {0x8ff150, 0xc00022c040})
	D:/Go/pkg/mod/github.com/brutella/dnssd@v1.2.2/responder.go:203 +0x1d4
github.com/brutella/dnssd.(*responder).Respond(0xc000210000, {0x8ff150, 0xc00022c040})
	D:/Go/pkg/mod/github.com/brutella/dnssd@v1.2.2/responder.go:113 +0x3ef
github.com/brutella/hap.(*Server).listenAndServe.func1()
	D:/Go/pkg/mod/github.com/brutella/hap@v0.0.14/server.go:206 +0x37
created by github.com/brutella/hap.(*Server).listenAndServe
	D:/Go/pkg/mod/github.com/brutella/hap@v0.0.14/server.go:205 +0x465

**Comment by zuozhehao** [comment]
https://github.com/brutella/dnssd/blob/master/mdns.go#L220
```go
n, cm, from, err := c.ipv4.ReadFrom(buf)  
if err != nil {
    continue
}
```
In the window, `cm` always returns nil.
`err` result message `read udp4 0.0.0.0:5353: use of closed network connection`
@brutella
